services:
  app:
    build: .
    container_name: home_node
    ports:
      - "8080:3000"
    environment:
      # Server settings
      - PORT=3000
      - BATCH_SIZE=34768

      # Frontend settings
      - FRONTEND_STREAMER_INACTIVITY_TIMEOUT=3000000
      - FRONTEND_STREAMER_CLEANUP_INTERVAL=1000000
      - FRONTEND_USE_LITTLE_ENDIAN=false

      - FRONTEND_SERVER_WS_URL=/api/v1/host/connect
      - FRONTEND_RECORD_INFO_WS_URL=/api/v1/host/@hostId/@itemId/metadata
      - FRONTEND_RECORD_DOWNLOAD_WS_URL=/api/v1/host/@hostId/@itemId/download

      - FRONTEND_PBKDF2_ITERATIONS=100000
      - FRONTEND_AES_KEY_LENGTH=256
      - FRONTEND_AES_IV_BYTES=12
      - FRONTEND_SALT_BYTES=16
    restart: unless-stopped
